server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
      baseUrl: http://localhost:9411/
  application:
    name: api-catalog
  data:
    mongodb:
      username: usrcatalogmongo
      password: pwdcatalogmongo
      database: catalogdevmongo
      port: 27018
      host: localhost

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}

management:
  endpoints:
    web:
      exposure:
        include: *