server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IlBono/esp-back-i-parcial-BonesiFederico
          default-label: develop
          force-pull: true
          search-paths: configData
